# Generated by Django 6.0.4 on 2026-05-29 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conversation', models.CharField(choices=[('tuteur', 'Tuteur — questions libres'), ('quiz', 'Quiz — révision guidée'), ('conseil', 'Conseil — analyse du planning')], default='tuteur', max_length=10)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('nb_messages', models.PositiveSmallIntegerField(default=0)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Élève'), ('assistant', 'NESIA')], max_length=10)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.conversationia')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['date_envoi'],
            },
        ),
    ]
