# Generated by Django 6.0.4 on 2026-05-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        ('planning', '0020_objectif_inclus_dans_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationia',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_ia', to='planning.chapitre'),
        ),
        migrations.AlterField(
            model_name='conversationia',
            name='type_conversation',
            field=models.CharField(choices=[('tuteur', 'Tuteur — questions libres'), ('seance', 'Séance — aide pendant le travail'), ('quiz', 'Quiz — révision guidée'), ('conseil', 'Conseil — analyse du planning')], default='tuteur', max_length=10),
        ),
    ]
