"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables depuis .env si présent (python-decouple)
try:
    from decouple import config as env
    _USE_DECOUPLE = True
except ImportError:
    _USE_DECOUPLE = False
    def env(key, default=None, cast=None):
        val = os.environ.get(key, default)
        return cast(val) if (cast and val is not None) else val

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-&1aw_jvnda(dlcydm*1alii4&(90st0cdg+=x@dfhj15hhm0@1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Packages tiers
    'rest_framework',
    'corsheaders',
    # Applications NESJAcademy
    'applications.utilisateurs',
    'applications.planning',
    'applications.diagnostic',
    'applications.analytique',
    'applications.ia',
]

MIDDLEWARE = [
    # CorsMiddleware DOIT être en premier pour injecter les headers CORS
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTH_USER_MODEL = 'utilisateurs.Utilisateur'

# ── Intelligence Artificielle (NESIA) ─────────────────────────────────────────
# Pour passer de Gemini à Anthropic : changer IA_FOURNISSEUR dans .env
IA_FOURNISSEUR             = env('IA_FOURNISSEUR', default='gemini')
GEMINI_API_KEY             = env('GEMINI_API_KEY', default='')
ANTHROPIC_API_KEY          = env('ANTHROPIC_API_KEY', default='')
IA_MAX_TOKENS              = env('IA_MAX_TOKENS', default=600, cast=int)
IA_MAX_MESSAGES_PAR_CONV   = env('IA_MAX_MESSAGES_PAR_CONV', default=50, cast=int)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Django REST Framework ──────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ── CORS (Cross-Origin Resource Sharing) ──────────────────────────────────────
# En développement on autorise toutes les origines (Flutter web + émulateur).
# En production, remplacer par CORS_ALLOWED_ORIGINS avec l'URL Railway.
CORS_ALLOW_ALL_ORIGINS = True

# ── Simple JWT ─────────────────────────────────────────────────────────────────
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=24),   # dev: 24h, prod: réduire à 15min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS':  True,                  # chaque refresh donne un nouveau refresh
    'BLACKLIST_AFTER_ROTATION': False,                # pas de blacklist en dev (pas de redis)
}