# Generated by Django 6.0.4 on 2026-05-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, help_text="Remplie quand l'élève arrête le chronomètre", null=True)),
                ('duree_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_focus', to='planning.chapitre')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_focus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Focus',
                'verbose_name_plural': 'Sessions Focus',
                'ordering': ['-date_debut'],
            },
        ),
    ]
