# Generated by Django 6.0.4 on 2026-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_codeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Âge de l'élève", null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.CharField(blank=True, help_text='Nom du lycée ou collège', max_length=200),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='systeme_scolaire',
            field=models.CharField(blank=True, choices=[('FR', 'Francophone'), ('EN', 'Anglophone'), ('TECH', 'Technique')], default='FR', help_text='Système scolaire suivi (MVP : FR uniquement)', max_length=4),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
