# Generated by Django 6.0.4 on 2026-05-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(blank=True, choices=[('3eme', '3ème (BEPC)'), ('Tle_A4', 'Terminale A4 (Littéraire)'), ('Tle_C', 'Terminale C (BAC)'), ('Tle_D', 'Terminale D'), ('Tle_TI', 'Terminale TI')], max_length=10),
        ),
    ]
