# Generated by Django 6.0.4 on 2026-05-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('choix_a', models.CharField(max_length=300)),
                ('choix_b', models.CharField(max_length=300)),
                ('choix_c', models.CharField(max_length=300)),
                ('choix_d', models.CharField(max_length=300)),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('niveau_difficulte', models.PositiveSmallIntegerField(default=1, help_text='1 = facile, 2 = moyen, 3 = difficile')),
                ('matiere', models.ForeignKey(limit_choices_to={'necessite_diagnostic': True}, on_delete=django.db.models.deletion.CASCADE, related_name='questions_diagnostic', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Question Diagnostic',
                'verbose_name_plural': 'Questions Diagnostic',
            },
        ),
        migrations.CreateModel(
            name='ResultatDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.DecimalField(decimal_places=1, help_text='Note sur 20 — sert à calculer la priorité de révision', max_digits=4)),
                ('date_diagnostic', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_diagnostic', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_diagnostic', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Résultat Diagnostic',
                'verbose_name_plural': 'Résultats Diagnostic',
                'ordering': ['-date_diagnostic'],
            },
        ),
    ]
