# Generated by Django 6.0.4 on 2026-05-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('systeme', models.CharField(choices=[('FR', 'Francophone'), ('EN', 'Anglophone'), ('TECH', 'Technique')], default='FR', max_length=4)),
                ('niveau', models.CharField(choices=[('3eme', '3ème (BEPC)'), ('Tle_C', 'Terminale C (BAC)')], max_length=10)),
                ('filiere', models.CharField(blank=True, help_text='Ex : C, D — laisser vide pour la 3ème', max_length=10)),
                ('coefficient_minesec', models.PositiveSmallIntegerField(help_text='Coefficient officiel utilisé dans le calcul de priorité')),
                ('necessite_diagnostic', models.BooleanField(default=True, help_text='False = matière secondaire, niveau fixé automatiquement à 10/20')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans l'application (plus petit = en premier)")),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position du chapitre dans la progression officielle de la matière')),
                ('duree_estimee_heures', models.PositiveSmallIntegerField(default=3, help_text='Durée estimée (en heures) pour maîtriser ce chapitre')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['matiere', 'ordre'],
                'unique_together': {('matiere', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='PlanEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_generation', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('eleve', models.OneToOneField(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='plan_etude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'Étude",
                'verbose_name_plural': "Plans d'Étude",
            },
        ),
        migrations.CreateModel(
            name='SessionEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('duree_minutes', models.PositiveSmallIntegerField(help_text="Durée calculée par l'algorithme selon heures_par_jour de l'élève")),
                ('type_session', models.CharField(choices=[('decouverte', 'Découverte'), ('revision_j1', 'Révision J+1'), ('revision_j3', 'Révision J+3'), ('revision_j7', 'Révision J+7'), ('revision_j14', 'Révision J+14')], default='decouverte', max_length=15)),
                ('completee', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, help_text="Remplie automatiquement quand l'élève marque la session comme terminée", null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planning.chapitre')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planning.planetude')),
            ],
            options={
                'verbose_name': "Session d'Étude",
                'verbose_name_plural': "Sessions d'Étude",
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pas_vu', 'Pas encore étudié'), ('en_cours', "En cours d'apprentissage"), ('maitrise', 'Maîtrisé')], default='pas_vu', max_length=10)),
                ('date_derniere_revision', models.DateField(blank=True, help_text='Date de la dernière session complétée sur ce chapitre', null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='planning.chapitre')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Chapitre',
                'verbose_name_plural': 'Progressions Chapitres',
                'unique_together': {('eleve', 'chapitre')},
            },
        ),
    ]
