# Generated by Django 6.0.4 on 2026-05-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cible', models.DecimalField(decimal_places=1, help_text="Note visée par l'élève (entre 10 et 20)", max_digits=4)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Objectif Matière',
                'verbose_name_plural': 'Objectifs Matières',
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
