# Generated by Django 6.0.4 on 2026-05-10 11:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_objectifmatiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lundi_dispo', models.BooleanField(default=True)),
                ('mardi_dispo', models.BooleanField(default=True)),
                ('mercredi_dispo', models.BooleanField(default=True)),
                ('jeudi_dispo', models.BooleanField(default=True)),
                ('vendredi_dispo', models.BooleanField(default=True)),
                ('samedi_dispo', models.BooleanField(default=True)),
                ('dimanche_dispo', models.BooleanField(default=False)),
                ('heures_lundi', models.PositiveSmallIntegerField(default=2)),
                ('heures_mardi', models.PositiveSmallIntegerField(default=2)),
                ('heures_mercredi', models.PositiveSmallIntegerField(default=2)),
                ('heures_jeudi', models.PositiveSmallIntegerField(default=2)),
                ('heures_vendredi', models.PositiveSmallIntegerField(default=2)),
                ('heures_samedi', models.PositiveSmallIntegerField(default=3)),
                ('heures_dimanche', models.PositiveSmallIntegerField(default=0)),
                ('creneau_prefere', models.CharField(choices=[('matin', 'Matin (6h - 12h)'), ('apres_midi', 'Après-midi (12h - 18h)'), ('soir', 'Soir (18h - 22h)')], default='soir', max_length=10)),
                ('heure_debut', models.TimeField(default=datetime.time(18, 0))),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('eleve', models.OneToOneField(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité Élève',
                'verbose_name_plural': 'Disponibilités Élèves',
            },
        ),
    ]
