# Generated by Django 6.0.4 on 2026-05-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_disponibiliteeleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=9)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponibilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='planning.disponibiliteeleve')),
            ],
            options={
                'verbose_name': 'Tranche horaire',
                'verbose_name_plural': 'Tranches horaires',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
