# Generated by Django 6.0.4 on 2026-05-12 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_tranche_horaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionetude',
            name='type_session',
            field=models.CharField(choices=[('decouverte', 'Découverte'), ('revision_immediate', 'Révision immédiate'), ('revision_j1', 'Révision J+1'), ('revision_j3', 'Révision J+3'), ('revision_j7', 'Révision J+7'), ('revision_j14', 'Révision J+14')], default='decouverte', max_length=20),
        ),
        migrations.CreateModel(
            name='CoursHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=9)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='emploi_du_temps', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_hebdomadaires', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Cours Hebdomadaire',
                'verbose_name_plural': 'Emploi du Temps',
                'ordering': ['jour', 'matiere'],
                'unique_together': {('eleve', 'matiere', 'jour')},
            },
        ),
    ]
