# Generated by Django 6.0.4 on 2026-05-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_cours_hebdomadaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionetude',
            name='tranche_horaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_prevues', to='planning.tranchehoraire'),
        ),
    ]
