# Generated by Django 6.0.4 on 2026-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_session_tranche_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='duree_exercices_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Durée de la session d'exercices (en minutes, 0 si pas d'exercices)"),
        ),
        migrations.AddField(
            model_name='matiere',
            name='duree_lecture_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Durée de la session de lecture/cours (en minutes)'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='necessite_exercices',
            field=models.BooleanField(default=False, help_text="True = l'algorithme génère 2 sessions par chapitre : lecture puis exercices"),
        ),
    ]
