# Generated by Django 6.0.4 on 2026-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_matiere_durees_initiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionetude',
            name='est_optionnelle',
            field=models.BooleanField(default=False, help_text="Session bonus suggérée si l'élève a du temps libre — non obligatoire"),
        ),
    ]
