# Generated by Django 6.0.4 on 2026-05-25 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_session_optionnelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('chapitre_actuel', models.ForeignKey(blank=True, help_text='Chapitre en cours avec le professeur cette semaine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_actuelles', to='planning.chapitre')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='positions_programme', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_programme', to='planning.matiere')),
            ],
            options={
                'verbose_name': 'Position Programme',
                'verbose_name_plural': 'Positions Programme',
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
