# Generated by Django 6.0.4 on 2026-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_tranche_matiere_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibiliteeleve',
            name='preference_etude',
            field=models.CharField(choices=[('matin', 'Matin — je suis plus concentré(e) le matin'), ('soir', 'Soir — je préfère étudier après les cours')], default='soir', help_text="Moment préféré pour les matières difficiles : l'algo place les matières lourdes à ce moment", max_length=5),
        ),
        migrations.AddField(
            model_name='objectifmatiere',
            name='niveau_difficulte',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facile — je comprends bien'), (2, "Moyen — j'ai quelques lacunes"), (3, "Difficile — j'ai du mal")], default=2, help_text='Difficulté ressentie (1=facile, 3=difficile) — sert à calculer le poids de la matière'),
        ),
    ]
