# Generated by Django 6.0.4 on 2026-05-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_objectif_difficulte_dispo_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionetude',
            name='est_pilier',
            field=models.BooleanField(default=False, help_text='Session fixe hebdomadaire pour une matière à fort coefficient (pilier)'),
        ),
    ]
