# Generated by Django 6.0.4 on 2026-05-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_session_est_abandonnee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.CharField(blank=True, choices=[('', '— (3ème, pas de filière)'), ('A4', 'A4 (Littéraire)'), ('C', 'C (Scientifique)'), ('D', 'D (Scientifique)'), ('TI', 'TI (Sciences Industrielles)')], help_text='Filière Terminale : A4, C, D, TI — laisser vide pour la 3ème', max_length=10),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.CharField(choices=[('3eme', '3ème (BEPC)'), ('Tle_A4', 'Terminale A4 (Littéraire)'), ('Tle_C', 'Terminale C (BAC Scientifique)'), ('Tle_D', 'Terminale D (BAC Scientifique)'), ('Tle_TI', 'Terminale TI (Sciences Industrielles)')], max_length=10),
        ),
    ]
