# Generated by Django 6.0.4 on 2026-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_alter_matiere_filiere_alter_matiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionetude',
            name='type_session',
            field=models.CharField(choices=[('anticipation', 'Anticipation (veille du cours)'), ('decouverte', 'Découverte'), ('revision_immediate', 'Révision immédiate'), ('revision_j1', 'Révision J+1'), ('revision_j3', 'Révision J+3'), ('revision_j7', 'Révision J+7'), ('revision_j14', 'Révision J+14')], default='decouverte', max_length=20),
        ),
    ]
