# Generated by Django 6.0.4 on 2026-05-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_add_anticipation_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='categorie',
            field=models.CharField(choices=[('hcc_pur', 'HCC pur (exercices intensifs)'), ('hcc_mixte', 'HCC mixte (exercices + lecture)'), ('lecture', 'Lecture / mémorisation'), ('sport', 'EPS / Sport')], default='lecture', help_text='Catégorie cognitive : hcc_pur → 90 min/session (Maths, Physique) ; hcc_mixte → 60 min (Chimie, SVT) ; lecture → durée libre (Philo, Géo…)', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='duree_lecture_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text="Durée recommandée de la révision immédiate pour les matières LECTURE (ignoré pour hcc_pur=90 min et hcc_mixte=60 min fixés par l'algo)"),
        ),
    ]
