# Generated by Django 6.0.4 on 2026-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_add_categorie_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectifmatiere',
            name='inclus_dans_planning',
            field=models.BooleanField(default=True, help_text='Si False, cette matière est exclue de la génération du planning'),
        ),
    ]
