# Generated by Django 6.0.4 on 2026-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_objectif_inclus_dans_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionchapitre',
            name='statut_classe',
            field=models.CharField(choices=[('non_aborde', 'Pas encore abordé en classe'), ('en_cours', 'En cours en classe'), ('termine', 'Terminé en classe')], default='non_aborde', help_text="Avancement du prof sur ce chapitre, déclaré par l'élève (fiable, indépendant de l'ordre)", max_length=12),
        ),
    ]
